[remote.github]
owner = "codenoobforreal"
repo = "easy-media-cli"

[changelog]
body = """
## What's Changed

{%- if version %} in {{ version | trim_start_matches(pat="v") }}{%- endif -%}
{% for commit in commits %}
  {% if commit.remote.pr_title -%}
    {%- set commit_message = commit.remote.pr_title -%}
  {%- else -%}
    {%- set commit_message = commit.message -%}
  {%- endif -%}
  * {{ commit_message | split(pat="\n") | first | trim }}\
    {% if commit.remote.username %} by @{{ commit.remote.username }}{%- endif -%}
    {% if commit.remote.pr_number %} in \
      [#{{ commit.remote.pr_number }}]({{ self::remote_url() }}/pull/{{ commit.remote.pr_number }}) \
    {%- endif %}
{%- endfor -%}

{%- if github -%}
{% if github.contributors | filter(attribute="is_first_time", value=true) | length != 0 %}
  {% raw %}\n{% endraw -%}
  ### New Contributors
{%- endif %}\
{% for contributor in github.contributors | filter(attribute="is_first_time", value=true) %}
  * @{{ contributor.username }} made their first contribution
    {%- if contributor.pr_number %} in \
      [#{{ contributor.pr_number }}]({{ self::remote_url() }}/pull/{{ contributor.pr_number }}) \
    {%- endif %}
{%- endfor -%}
{%- endif -%}

{% if version %}
    {% if previous.version %}
      **Full Changelog**: {{ self::remote_url() }}/compare/{{ previous.version }}...{{ version }}
    {% endif %}
{% else -%}
  {% raw %}\n{% endraw %}
{% endif %}

{%- macro remote_url() -%}
  https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}
{%- endmacro -%}
"""

# 模板渲染后的内容去除首尾空白字符
trim = true
footer = """
<!-- generated by git-cliff -->
"""
# 定义多个正则表达式后处理器，在最终输出前对变更日志进行二次修改（例如替换占位符）
postprocessors = []

[git]
# 是否启用约定式提交规范（Conventional Commits）解析
conventional_commits = false
# 排除不符合约定式提交规范的提交
filter_unconventional = false
# 将提交消息按换行符拆分成多个独立的提交条目（适用于一条提交消息中包含多个逻辑变更的情况）
split_commits = false
# 定义一组提交消息的预处理正则表达式，在解析之前对原始提交消息进行修改。这里的正则 \((\w+\s)?#([0-9]+)\) 匹配形如 ( #123) 或 (fix #456) 这样的片段（括号内可能有单词和空格，然后一个井号加数字），并将这些片段替换为空字符串（即删除）。这通常用于移除提交消息中携带的 issue/PR 引用，避免干扰后续的处理，因为这些引用可能已在别处（如远程数据）中处理。
commit_preprocessors = [{ pattern = '\((\w+\s)?#([0-9]+)\)', replace = "" }]
# 保留那些匹配了任何提交解析器的提交。由于这里没有定义额外的解析器，该选项无实际作用
filter_commits = false
# 控制版本的排序方式。若为 true，则按拓扑顺序（基于分支合并关系）排列版本；若为 false，则按时间顺序（提交日期）排列。这里为 false，即按时间顺序
topo_order = false
# 控制每个版本内的提交按何种顺序展示。可选值为 "newest"（最新的在前）或 "oldest"（最旧的在前）。这里设为 "newest"，即提交按从新到旧排列
sort_commits = "newest"
